import React from "react";
import { Link } from "wouter";
import { ArrowRight, FileText, Info, ShieldCheck } from "lucide-react";

const components = [
  ["Firsthand Knowledge","4/20","The deponent, CAS Manager, is a manager covering for the actual assigned worker (CAS Worker) and expressly states she lacks personal knowledge of most matters, relying instead on file records and third-party accounts (para 1-4)."],
  ["Source Reliability","9/15","Most substantive factual content (paras 6-28) is attributed to a single named source, Parent B, self-reporting during an in-person meeting on Sept 30, 2025, which allows the source to be identified and tested but is one-sided and undated as to when underlying events occurred versus when reported."],
  ["Corroboration","10/15","Several of Parent B's narrative statements about dated incidents are independently corroborated by attached police occurrence reports, though other statements about finances, caregiving allocation, and counselling have no independent documentary corroboration."],
  ["Documentary Support","11/15","Nine police occurrence reports (Exhibits A-I) are attached and dated, giving concrete documentary backing for the domestic-incident timeline, though additional 2020-2021 records and Sarnia OPP records are described but not attached."],
  ["Internal Consistency","6/10","The report identifies tension between Parent B's narrative describing Parent A as okay with children outside his obsessions and the more alarming characterization in Exhibit I, where the CAS Worker is recorded expressing concerns with him being alone with his children."],
  ["Contradictory Evidence Handling","3/10","The affidavit does not flag or reconcile police notes stating no grounds to apprehend against the Society's protection concerns, including a same-day police finding of no grounds for apprehension while a Form 2 was reportedly being pursued."],
  ["Legal Authority Verification","2/10","The affidavit references compliance with clinical practice standards arising from the CYFSA without citing a specific section, and the legal authority for the relief sought is not verified within the document."],
  ["Procedural Documentation","2/5","The affidavit is commissioned and dated and exhibits are marked and sworn, but it notes the primary caseworker is unavailable and requests leave for a further affidavit, signaling an incomplete evidentiary record at the time of swearing."]
];

const flags = [
  ["HEARSAY [AFFECTS EVIDENTIARY WEIGHT]","On September 30, 2025, Parent B attended the Agency and advised me of the following;","Paragraphs 7-28 are the deponent's summary of an out-of-court statement by Parent B; the source report says this kind of hearsay is often permitted in motion affidavits where the source is named, while persuasive weight depends on source reliability and corroboration.","Ask whether Parent B will be available for cross-examination and compare the account against independently dated records, including text messages, bank records and day-care registration records for the claims identified in the report.","Ask counsel whether to request particulars or cross-examination on the specific factual claims, particularly financial and caregiving-allocation claims without attached documentary support."],
  ["CONTRADICTORY EVIDENCE NOT ADDRESSED [WORTH RAISING WITH COUNSEL]","There were no grounds for apprehension at this time as Parent A was not a danger to himself or others.","This police conclusion in Exhibit I directly precedes the affidavit's account that the Society was moving to supervised visits only and that the CAS Worker intended to pursue a Form 2. The source report identifies this as a factual tension worth raising, not a confirmed procedural violation.","Request the full Society file notes explaining the internal basis for moving to supervised access notwithstanding the police finding of no apprehension grounds on the same day.","Ask counsel whether the apparent inconsistency between the police assessment and the Society's decision should be raised as a point going to the weight of the protection concerns."],
  ["INFORMAL RESTRICTION VS. FORMAL PROCESS [WORTH RAISING WITH COUNSEL]","Due to this, F&CS is only going to allow him to have supervised visits with","The source report labels this a theory to test, not settled law: an argument could be made that an informal worker-driven restriction outside a court order or documented safety plan should have accompanying procedural documentation, but it does not claim a specific CYFSA notice or consent requirement was established.","Request any written safety plan, notice or consent form associated with the access restriction and the date it was communicated to Parent A.","Ask counsel whether Ontario courts require a documented safety plan or formal notice before a restriction of this kind and whether any absence is worth raising."],
  ["DEPONENT PERSONAL KNOWLEDGE LIMITATION [WORTH RAISING WITH COUNSEL]","I have personal knowledge of some of the matters hereinafter deposed to. To the extent that I do not have personal knowledge of some of the matters hereinafter deposed to, I rely upon:","The source report says the affidavit's near-total reliance on second-hand information from a covering manager may be a fair subject for a weight or reliability argument, while not treating that as a settled admissibility conclusion.","Confirm which paragraphs are based on direct personal observation versus file review or third-party report, and request the assigned CAS Worker's own affidavit referenced in paragraph 1.","Ask counsel whether to request the promised follow-up affidavit from the assigned CAS Worker before this affidavit is relied upon at a hearing."],
  ["UNSUPPORTED CLAIM [AFFECTS EVIDENTIARY WEIGHT]","Parent B advised that the worker may have understood she was the primary caregiver for Child A as she makes 90 percent of the decisions for him.","The source report characterizes this as a self-reported estimate by one party about her own caregiving role with no attached corroborating documentation such as school registration or medical appointment records.","Request supporting documentation such as school registration forms, medical/dental records or day-care enrollment records showing which parent completed these tasks.","Ask counsel whether to request disclosure of the underlying records referenced to test this claim."],
  ["INCOMPLETE DISCLOSURE [WORTH RAISING WITH COUNSEL]","The Society has received records from 2020 and 2021, if this matter proceeds to a temporary care hearing the records would be filed.","The source report treats this as a fairness point worth raising with counsel rather than a confirmed procedural violation because the affidavit references but does not include records described as relevant to significant conflict.","Ask Society counsel for the specific content, source and date of the 2020-2021 records and whether they will be produced before the next hearing.","Ask counsel whether to request early production or particulars of the referenced records."],
  ["MISSING CORROBORATING RECORD [AFFECTS EVIDENTIARY WEIGHT]","The Society has not received his records from the Sarnia OPP.","The source report treats this as an acknowledged gap in the record rather than an admitted violation and cautions that incompleteness is not proof of wrongdoing by any party.","Ask whether the Sarnia OPP records have since been obtained and, if so, request disclosure and an opportunity to review them before any hearing where they may be relied upon.","Ask counsel to follow up on the status of the outstanding Sarnia OPP records referenced in the affidavit."]
];

const verify = [
"The original Form 8 (Application) and any prior court orders/endorsements, to establish procedural history and adjournment dates relevant to s.94(1).",
"The full, un-redacted police occurrence reports referenced as Exhibits A-I, including the apparent Exhibit G date typo flagged by the analyzer.",
"Any Society safety plan, service plan, or supervision-order documentation showing the basis and timing for the decision to move Parent A to supervised-only visits.",
"Whether the Form 2 application referenced in Exhibit I was ever filed and, if so, its outcome.",
"Parent B's actual work-schedule records and communications with the Society regarding visit logistics.",
"Records of the prior Sarnia CAS supervision order concerning Child B and whether that history bears on the current proceeding.",
"The full CAS file notes regarding any kinship search or family-finding efforts for Child A."
];

const lawyerQuestions = [
"Does the pattern of police-documented incidents, considered together with repeated no-grounds-for-apprehension findings, actually support a s.74(2) need-of-protection finding, or does it fall short of that threshold?",
"Did the decision to restrict Parent A to supervised visits require a court order at the time, or was it within the Society's administrative authority pending a hearing?",
"How much weight is likely to be given to paragraphs sourced from Parent B's statements to the affiant rather than the affiant's direct observation?",
"Should the Society's complete file, including kinship/family-finding records, be requested to determine whether alternatives were explored?",
"Given the apparent date error in Exhibit G, should confirmation/correction of the exhibit and any other exhibit-accuracy concerns be requested before the hearing?",
"Is a motion to compel the appearance of the assigned CAS Worker appropriate given that this affidavit is sworn by a manager without personal knowledge of most events?",
"Does the possible Form 2 application referenced in Exhibit I have any bearing on the child-protection matter, and should its status be clarified?"
];

const missing = [
"Direct observation by the CAS Manager of either child's home environment, well-being, or interactions with either parent; the affidavit is substantially a summary of secondhand reports and the Society's written record.",
"Any statement from the children themselves about their views or preferences.",
"A clear timeline of exactly when the decision to restrict Parent A to supervised visits was made, by whom, and under what authority.",
"Documentation of any kinship, extended-family, or alternative-placement considerations for either child.",
"Confirmation of whether the assigned CAS Worker's return affidavit has since been filed and what it adds or corrects.",
"Any psychological, psychiatric, or other assessment of Parent A's mental health, as opposed to lay observations and the Society's characterization.",
"Clarification of the apparent inconsistency between Parent B's statement that she makes 90 percent of decisions for Child A and an occurrence report's note that Parent A has full custody of the child."
];

export default function AnalysisExample() {
 return <div className="mx-auto max-w-6xl space-y-8 pb-16">
  <header data-tts-read className="rounded-3xl bg-gradient-to-br from-slate-950 via-brand-950 to-brand-800 p-7 text-white md:p-10">
   <p className="text-xs font-bold uppercase tracking-[0.2em] text-brand-200">PARENTSHIELD • EVIDENCE STRENGTH AUDIT</p>
   <h1 className="mt-3 font-display text-4xl font-black">File Analysis &amp; Evidence Strength Report</h1>
   <p className="mt-4 max-w-4xl leading-relaxed text-slate-200">This public example reproduces the actual analyzer-generated report content. Only identifying names, child/family identifiers and the court-file number are replaced with neutral labels.</p>
   <div className="mt-5 rounded-xl border border-white/20 bg-white/10 p-4 text-sm"><strong>Redaction key:</strong> CAS Manager, CAS Worker, Parent A, Parent B, Child A and Child B replace identifying names. No synthetic allegations, findings, scores or analysis have been added.</div>
  </header>

  <section data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
   <div className="flex gap-3"><FileText className="mt-1 h-5 w-5 text-brand-600"/><div><h2 className="font-display text-2xl font-bold">Document Checked</h2><p className="mt-2 text-sm text-slate-600"><strong>Affidavit (General) of CAS Manager, sworn September 30, 2025</strong> • Type: CAS Supporting Affidavit (Form 14A) with Police Occurrence Report Exhibits • Date of Audit: Current</p></div></div>
  </section>

  <section><h2 className="font-display text-2xl font-black">📊 Educational Evidence Strength Summary</h2>
   <div data-tts-read className="mt-4 rounded-2xl border border-slate-200 bg-white p-6"><div className="flex flex-wrap items-end gap-4"><strong className="text-5xl text-brand-900">47 / 100</strong><span className="max-w-2xl text-sm text-slate-600">Evidence Strength Index. Educational heuristic assessing the strength of evidence documented in this file. It is not a legal admissibility ruling, does not determine the truth of allegations, and does not determine the legal merits of the case.</span></div></div>
   <div className="mt-4 grid gap-4 md:grid-cols-2">{components.map((r,i)=><article data-tts-read key={i} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><h3 className="font-bold">{r[0]}</h3><strong className="text-brand-800">{r[1]}</strong></div><p className="mt-2 text-sm leading-relaxed text-slate-700">{r[2]}</p></article>)}</div>
   <div data-tts-read className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-5"><strong>Information Completeness: 62/100</strong><p className="mt-2 text-sm">Measures how much relevant information is contained in the reviewed document. It is separate from the Evidence Strength Index and is not an admissibility or legal-merits score. A low score means the document contains gaps, unsupported assertions, limited firsthand knowledge, contradictions, or insufficient documentation. It does not mean the document is false or inadmissible. A high score does not establish legal correctness or admissibility.</p></div>
  </section>

  <section><h2 className="font-display text-2xl font-black">⚠️ Hearsay &amp; Subjective Opinion Red Flags</h2><p className="mt-2 text-sm text-slate-600">The following assertions or opinions were extracted from the analyzed file. Identifying names inside quotations are redacted.</p><div className="mt-4 space-y-4">{flags.map((f,i)=><article data-tts-read key={i} className="rounded-2xl border border-rose-200 bg-white p-6"><h3 className="font-black text-amber-900">{f[0]}</h3><p className="mt-2 text-xs font-bold uppercase text-amber-800">⚠️ STATUTE CITATION UNVERIFIED — CONFIRM EXACT SECTION WITH COUNSEL BEFORE RELYING ON THIS.</p><h4 className="mt-4 font-bold">Quote Detected in File</h4><blockquote className="mt-2 border-l-4 border-slate-300 pl-4 font-mono text-sm font-semibold">“{f[1]}”</blockquote><h4 className="mt-4 font-bold">Educational Advisory</h4><p className="mt-1 text-sm leading-relaxed">{f[2]}</p><h4 className="mt-4 font-bold">Verification Requirement</h4><p className="mt-1 text-sm leading-relaxed">{f[3]}</p><div className="mt-4 rounded-xl border border-dashed border-slate-300 p-4 text-sm"><strong>🛡️ Self-Defense Counter-Action Step:</strong> {f[4]}</div></article>)}</div></section>

  <section><h2 className="font-display text-2xl font-black">⚖️ Statutory Protection Threshold Appraisals</h2>
   <div data-tts-read className="mt-4 rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">CYFSA s. 81 — Application / Child Protection Proceeding Authority</h3><p className="mt-1 font-bold text-amber-800">Inconclusive</p><p className="mt-3 text-sm leading-relaxed">The affidavit is filed in support of a motion within an already-existing child protection proceeding, referencing a prior affidavit of the CAS Worker sworn September 16, 2025 and a court appearance on September 25, 2025. The source report says s.81 concerns procedural authority/mechanics rather than the substantive need-of-protection threshold and that the originating application is required to determine whether the proceeding was properly commenced. It separately identifies s.74 as governing whether a child is in need of protection.</p><p className="mt-3 text-xs font-semibold text-amber-800">⚠️ Statute citation unverified — confirm exact subsection with counsel before relying on this.</p></div>
   <div data-tts-read className="mt-4 rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Child in Need of Protection grounds (CYFSA s. 74)</h3><p className="mt-1 font-bold text-amber-800">Inconclusive</p><p className="mt-3 text-sm leading-relaxed">The affidavit describes repeated police-attended domestic disputes, reported mental-health/paranoia concerns and an incident where a child left the residence unsupervised. The attached police reports also repeatedly record no grounds for apprehension or no child-care safety concerns. The source report says the records may still support lower-level protection concerns, but whether the cumulative pattern meets a specific s.74(2) paragraph is a legal determination for the court and counsel.</p><p className="mt-3 text-xs font-semibold text-brand-800">Source law authority identified in source report: CYFSA 2017, Section 74.</p></div>
   <div data-tts-read className="mt-4 rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Duty to Report standard vs Direct evidence (CYFSA s. 125)</h3><p className="mt-1 font-bold text-rose-700">Yes</p><p className="mt-3 text-sm leading-relaxed">Several paragraphs rely on secondhand reports from Parent B. The affidavit expressly discloses that information is sourced from third parties or the Society's written record and attributes statements to Parent B. The source report says this is disclosed hearsay affecting weight rather than a representation that the material is direct observation.</p><p className="mt-3 text-xs font-semibold text-brand-800">Source law authority identified in source report: CYFSA 2017, Section 125.</p></div>
   <div data-tts-read className="mt-4 rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Kinship / Family-Based Alternatives — Documentation Check</h3><p className="mt-1 font-bold text-amber-800">Not Determinable From This Document</p><p className="mt-3 text-sm leading-relaxed">The affidavit does not document consideration of kinship, extended-family, customary-care, Indigenous or other family-based alternatives to the arrangement described. The source report expressly cautions that absence from this affidavit does not establish that the Society failed to consider alternatives; the full Society file, kinship-search records and prior court orders or plans of care would be required.</p></div>
  </section>

  <section><h2 className="font-display text-2xl font-black">⏳ Statutory Timelines &amp; Procedural Violations</h2><div className="mt-4 space-y-4">
   <article data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">30-Day Adjournment Limit (CYFSA s. 94(1))</h3><p className="mt-3 text-sm leading-relaxed">The document references a September 25, 2025 court date, the CAS Worker's prior affidavit sworn September 16, and this affidavit dated September 30. <strong>Not Determinable From This Document.</strong> The document does not disclose the original hearing date, the date of any adjournment order, or whether all parties/caregivers consented to an adjournment exceeding 30 days. The source report says a full court endorsement/order history is required.</p><p className="mt-3 text-sm font-semibold text-amber-800">🛡️ Parent Action: Ask counsel to pull the full court endorsement history and confirm whether any adjournment exceeded 30 days without consent and, if so, whether an objection was raised on the record.</p></article>
   <article data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Court hearing timeline following apprehension without warrant</h3><p className="mt-3 text-sm leading-relaxed">No apprehension of either child is described anywhere in the affidavit or exhibits. Multiple police occurrence reports explicitly state no grounds to apprehend or equivalent. The source report marks this <strong>Not applicable — child in home care</strong> and explains that the arrangement described is supervised access restrictions rather than apprehension.</p><p className="mt-3 text-sm font-semibold text-amber-800">🛡️ Parent Action: If circumstances change and either child is apprehended, ask counsel immediately to confirm the exact CYFSA section governing the post-apprehension court-appearance deadline and calendar that date independently.</p></article>
   <article data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">Child Ombudsman Access &amp; Continuous Care Rights</h3><p className="mt-3 text-sm leading-relaxed">The affidavit and exhibits do not indicate either child is in Society-managed out-of-home care. The source report marks this not determinable/not applicable on the stated facts and discusses the Ombudsman-related legislation identified in the analyzer output.</p><p className="mt-3 text-sm font-semibold text-amber-800">🛡️ Parent Action: Ask counsel whether the legislation identified in the report provides a route to file a complaint with the Ontario Ombudsman about the Society's handling of the file, separate from the court process.</p></article>
   <article data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-bold">300-Day Presumption of Parentage</h3><p className="mt-3 text-sm leading-relaxed">The affidavit names and treats Parent A and Parent B as parents and raises no parentage dispute. The source report records this as checked and compliant on the facts presented and says the parentage-presumption provisions do not appear factually engaged.</p><p className="mt-3 text-sm font-semibold text-amber-800">🛡️ Parent Action: Confirm both parents are correctly named on all notices and orders and that no parentage-presumption issue affects standing.</p></article>
  </div></section>

  <section data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-display text-2xl font-black">✊ Human &amp; Charter Rights Observations</h2><p className="mt-4 text-sm leading-relaxed"><strong>Section 7:</strong> The source report says the cumulative narrative, including reported mental-health episodes involving Parent A and the resulting move to supervised-only access, engages liberty and security-of-the-person interests in the parent-child relationship. It identifies as worth raising with counsel whether the informal supervised-access decision adequately respected due-process protections and expressly calls this a fact-specific procedural-fairness question requiring the actual court record.</p><p className="mt-4 text-sm leading-relaxed"><strong>Section 15:</strong> The source report notes repeated framing of Parent A's conduct through mental-health terminology and identifies as worth raising with counsel whether restrictions were proportionate to demonstrated risk or disproportionately influenced by mental-health status. It expressly labels this a legal argument to test, not an established finding.</p><p className="mt-4 text-sm leading-relaxed"><strong>Indigenous / First Nations / Inuit / Métis heritage:</strong> The analyzed document contains no information about Indigenous status, heritage, band/community affiliation, customary care or community consultation. The source report marks this as Missing Evidence / Not Determinable From This Document and says the Society's intake and family-service records would need review.</p></section>

  <section data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-display text-2xl font-black">📋 Practical Verification &amp; Next Steps Guide</h2><h3 className="mt-5 font-bold">Information to Verify &amp; Double-Check</h3><ul className="mt-3 list-disc space-y-3 pl-5 text-sm leading-relaxed">{verify.map((x,i)=><li key={i}>{x}</li>)}</ul><h3 className="mt-7 font-bold">Specific Questions for Your Retained Lawyer</h3><ol className="mt-3 list-decimal space-y-3 pl-5 text-sm leading-relaxed">{lawyerQuestions.map((x,i)=><li key={i}>{x}</li>)}</ol></section>

  <section data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-display text-2xl font-black">Inconsistencies or Missing Casework Elements</h2><ul className="mt-4 list-disc space-y-3 pl-5 text-sm leading-relaxed">{missing.map((x,i)=><li key={i}>{x}</li>)}</ul></section>

  <section data-tts-read className="rounded-2xl border border-amber-200 bg-amber-50 p-6"><div className="flex gap-3"><Info className="mt-1 h-5 w-5 text-amber-800"/><div><h2 className="font-display text-xl font-black">Public redaction notice</h2><p className="mt-2 text-sm leading-relaxed text-amber-950">This is the analyzer's real report content with identifying names, child/family identifiers and the court-file number redacted or replaced by neutral labels. No fictional allegations or synthetic analyzer findings are included.</p></div></div></section>

  <section data-tts-read className="rounded-2xl border border-slate-200 bg-white p-6 text-sm leading-relaxed"><strong>MANDATORY LEGAL EDUCATIONAL STATEMENT:</strong> This document is generated for informational/educational objectives only under secondary statutory guidelines of the Child, Youth and Family Services Act (CYFSA) S.O. 2017, Chapter 14. This does not represent formal counsel or legal aid representations. Please immediately secure local, verified counsel from the Law Society of Ontario or Legal Aid Ontario to represent your case before the Court.</section>

  <section className="rounded-3xl bg-slate-950 p-7 text-white md:p-10"><ShieldCheck className="h-7 w-7 text-brand-300"/><h2 className="mt-3 font-display text-3xl font-black">Analyze your own document</h2><p className="mt-3 max-w-2xl text-slate-300">Run your document through the CYFSA Document Analyzer &amp; Parent Educator.</p><Link href="/document-analyzer"><span className="mt-6 inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3 font-bold text-brand-900">TRY OUR ANALYZER &amp; EDUCATOR <ArrowRight className="h-5 w-5"/></span></Link></section>
 </div>;
}
